import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

public class MonopolyModel {
    /**
     * The Monopoly class
     *
     * This class is the brains of the game,
     * it controls all the functions and how the players
     * move about the board.
     *
     * @attribute board type Board, is one instance
     * @attribute players type ArrayList<Player> contains the list
     * players that are currently playing
     * @attribute die type Dice is the die that will be used for the game
     * @attribute playerTurn type int is used to determine whose turn it is
     */
    private final Board board;
    private final List<Player> players;
    private final Dice die;
    private boolean validCommand = false;
    private boolean running = true;
    int playerTurn;
    private MonopolyView view;

    public MonopolyModel() {
        this.board = new Board();
        this.die = new Dice();
        this.players = new ArrayList<>();
        this.playerTurn = 0;
    }

    public Board getBoard() {
        return board;
    }

    public List<Player> getPlayers() {
        return players;
    }

    public void addMonopolyView(MonopolyView mv){
        view = mv;
    }

    /**
     * This method is called if a player goes bankrupt, it first removes all the players ownerships and
     * then removes the player from the game.
     *
     * Created and documented by Matthew Belanger
     */
    public void removePlayer() {
        this.players.get(this.playerTurn).removeProperties();
        this.players.remove(this.playerTurn);
    }

    /**
     * Roll() method rolls the dice
     * @return the random int generated by rolling the die
     *
     * Created and documented by Nathan MacDiarmid - 101098993
     */
    public int roll() {
        return this.die.roll();
    }

    /**
     * This method is used to get the player whose turn it is
     * @return the current Player object
     *
     * Created and documented by Matthew Belanger - 101144323 and Tao - 101164153
     */
    public Player getPlayer(){
        return this.players.get(playerTurn);
    }

    /**
     * This method returns a string representation of the property that the Player is currently on
     * @return string representation of a Property
     *
     * Created and documented by Matthew Belanger - 101144323 and Tao - 101164153
     */
    public String getPropertyInfo(){
        return this.board.getProperty(this.getPlayer().getPosition()).toString();
    }

    /**
     * This method returns the owner (which is a Player object) of the Property the Player is currently on
     * @return Player object
     *
     * Created and documented by Matthew Belanger - 101144323 and Tao - 101164153
     */
    public Player getPropertyOwner(){
        return this.board.getProperty(this.getPlayer().getPosition()).getOwner();
    }

    /**
     * This method verifies that the property is available to buy.
     *
     * Created and documented by Nathan MacDiarmid - 101098993
     */
    public boolean checkProperty() {
        if (this.getPropertyOwner() != null) {
            if (this.getPlayer() != this.getPropertyOwner()) {
                payRent();
            }
            return false;
        }

        if (handleEmptyProperties()) {
            return false;
        }

        return true;
    }

    /**
     * This method allows players to buy properties.
     * @param selection a selection from a JOptionPane
     * @return a boolean value whether the property was bought.
     *
     * Created and documented by Matthew Belanger - 101144323 and Tao - 101164153
     * Refactored and re-documented by Nathan MacDiarmid - 101098993
     */
    public boolean buyProperty(int selection) {
        if (selection == JOptionPane.YES_OPTION) {
            return this.getPlayer().buy(this.board.getProperty(this.getPlayer().getPosition()));
        }
        return true;
    }

    /**
     * This method adds money to the Player the rent is being paid too. This is done by getting the Player who owns the
     * property the current Player is on and then calling the addMoney() method on the Player owning the property.
     *
     * Created and documented by Matthew Belanger - 101144323 and Tao - 101164153
     * Refactored by Nathan MacDiarmid - 101098993
     */
    public void payRent(){
        this.board.getProperty(this.getPlayer().getPosition()).getOwner().addMoney(this.board.getProperty(this.getPlayer().getPosition()).getRent());
        this.getPlayer().rent(this.board.getProperty(this.getPlayer().getPosition()));
    }

    /**
     * This method is the logic is the logic behind adding players to the list
     * of players.
     *
     * Created and documented by Nathan MacDiarmid - 101098993
     */
    public void addPlayer(String name) {
        players.add(new Player(name));
    }

    /**
     * Handles the empty properties that don't do anything at the moment.
     * Current empties: Go and Free Parking
     * @return boolean value whether a player landed on one of these properties.
     *
     * Created and documented by Nathan MacDiarmid - 101098993
     */
    public boolean handleEmptyProperties() {
        if (this.board.getProperty(this.getPlayer().getPosition()).equals(this.board.getProperty(0))) {
            return true;
        }
        else return this.board.getProperty(this.getPlayer().getPosition()).equals(this.board.getProperty(12));
    }

    /**
     * This method handles the logic behind a player turn, it will be called by view and will increment the player position
     * check the property the player is on as well as the players money and if someone has won. Finally it will change the turn
     * to the next player and then update the view.
     * @param rollValue
     *
     * Created and documented by Matthew Belanger - 101144323
     */
    public void playTurn(int rollValue){
        this.getPlayer().addPosition(rollValue);
        //Increase playerTurn to pass the turn to the next player
        view.checkAvailability();
        if(getPlayer().getMoney() <= 0){
            view.playerEliminated();
            this.removePlayer();
        }
        if(this.players.size() == 1){
            view.playerWin();
        }
        this.playerTurn = (this.playerTurn + 1) % this.players.size();
        view.updateStatus();
    }

}